name: Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm lint 
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying project"